CREATE TYPE "Role_new" AS ENUM (
  'PLATFORM_ADMIN',
  'TOURNAMENT_ORGANIZER',
  'TEAM_MANAGER_COACH',
  'PLAYER'
);

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new"
USING (
  CASE
    WHEN "role"::text IN ('COACH', 'TEAM_MANAGER') THEN 'TEAM_MANAGER_COACH'
    ELSE "role"::text
  END
)::"Role_new";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'PLAYER';
DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";
